<?php declare(strict_types=1); ?>
<!doctype html><html lang="da" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#06110e"><title>Analyse & rapporter · Solportalen</title><link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/assets/css/app.css?v=8"><link rel="stylesheet" href="/assets/css/analytics.css?v=1"><script src="/assets/js/analytics.js?v=1" defer></script></head>
<body class="analytics-page"><header><a class="brand" href="/"><span class="sunmark"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg></span><div><strong>Solportalen</strong><small>Analyse & rapporter</small></div></a><div class="status"><span class="pill source-pill">24 MDR. LOKAL HISTORIK</span><span class="live-dot"></span><span id="clock"></span></div></header>
<div class="layout"><nav><div class="nav-label">SOLPORTALEN</div><a href="/"><span>◉</span>Overblik</a><a class="active" href="/analytics"><span>▥</span>Analyse & rapporter</a><a href="/weather"><span>☀</span>Vejrprognose</a><a href="/prices"><span>↗</span>Elprisprognose</a><a href="/suppliers"><span>⌕</span>Leverandørvagt</a><div class="nav-label">ANLÆG</div><a href="/commissioning"><span>⌘</span>Commissioning</a><a href="/wallboard"><span>□</span>Wallboard</a></nav>
<main><section class="report-hero"><div><p class="eyebrow">ENERGIREGNSKAB</p><h1>Se hvad anlægget faktisk har leveret</h1><p>Produktion, forbrug, batteri og net samlet i ét historisk overblik.</p></div><div class="range-picker" role="group" aria-label="Rapportperiode"><button data-range="24h">24 t.</button><button data-range="7d">7 dage</button><button class="active" data-range="30d">30 dage</button><button data-range="12m">12 mdr.</button><button data-range="24m">24 mdr.</button></div></section>
<section class="report-kpis"><article class="report-kpi solar"><span>Solproduktion</span><b id="report-pv">—</b><small>produceret i perioden</small></article><article class="report-kpi home"><span>Husets forbrug</span><b id="report-load">—</b><small>samlet energibehov</small></article><article class="report-kpi autonomy"><span>Selvforsyning</span><b id="report-self-sufficiency">—</b><small>dækket uden nettoimport</small></article><article class="report-kpi grid"><span>Netbalance</span><b id="report-net">—</b><small id="report-net-label">import minus eksport</small></article></section>
<section class="analytics-grid"><article class="analytics-card wide"><div class="chart-heading"><div><p class="eyebrow">ENERGI OVER TID</p><h2>Produktion og forbrug</h2></div><span id="history-meta">Henter lokale målinger…</span></div><div class="legend"><span class="pv">Sol</span><span class="load">Hus</span><span class="battery">Batteri</span><span class="gridline">Net</span></div><div class="chart-scroll"><canvas id="history-chart" height="320"></canvas></div></article>
<article class="analytics-card"><p class="eyebrow">ENERGIENS VEJ</p><h2>Egenudnyttelse</h2><div class="ring" id="self-ring" style="--value:0"><div><b id="report-self-consumption">—</b><small>af solproduktionen<br>brugt lokalt</small></div></div><div class="split-stats"><span><small>Fra nettet</small><b id="report-import">—</b></span><span><small>Til nettet</small><b id="report-export">—</b></span></div></article>
<article class="analytics-card"><p class="eyebrow">BATTERIARBEJDE</p><h2>Ladning og afladning</h2><div class="battery-bars"><div><span>Opladet</span><i><em id="charge-bar"></em></i><b id="report-charge">—</b></div><div><span>Afladet</span><i><em id="discharge-bar"></em></i><b id="report-discharge">—</b></div></div><p class="method-note">Viser målte energistrømme – ikke et beregnet løfte om besparelse.</p></article>
<article class="analytics-card wide"><div class="chart-heading"><div><p class="eyebrow">DAG FOR DAG</p><h2>Dagligt energiregnskab</h2></div><button id="print-report" class="print-button">Udskriv rapport</button></div><div class="chart-scroll daily"><canvas id="daily-chart" height="290"></canvas></div><div class="report-foot"><span id="report-period">—</span><span id="report-method">—</span></div></article></section></main></div><footer>Data beregnes lokalt · <a href="/">Tilbage til live-overblik</a></footer></body></html>
