<?php declare(strict_types=1); ?>
<!doctype html><html lang="da" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#06110e"><title>Intelligent styring · Solportalen</title><link rel="stylesheet" href="/assets/css/app.css?v=9"><link rel="stylesheet" href="/assets/css/automation.css?v=1"><script src="/assets/js/automation.js?v=1" defer></script></head><body>
<header><a class="brand" href="/"><span class="sunmark">☀</span><div><strong>Solportalen</strong><small>Intelligent styring</small></div></a><div class="status"><span class="pill read-pill">LOKAL AUTOMATIK</span><span class="live-dot"></span></div></header>
<div class="layout"><nav><div class="nav-label">SOLPORTALEN</div><a href="/"><span>◉</span>Overblik</a><a href="/analytics"><span>▥</span>Analyse & rapporter</a><a class="active" href="/settings/automation"><span>✦</span>Intelligent styring</a><a href="/weather"><span>☀</span>Vejrprognose</a><a href="/prices"><span>↗</span>Elprisprognose</a><div class="nav-label">ANLÆG</div><a href="/commissioning"><span>⌘</span>Commissioning</a></nav><main class="automation-page">
<section class="settings-hero"><p class="eyebrow">DRIFTSTILSTAND</p><h1>Lad Solportalen planlægge energien</h1><p>En ny plan beregnes og sendes automatisk til Growatt-anlægget én gang dagligt. Alle writes læses tilbage og verificeres som hidtil.</p></section>
<form id="automation-form"><section class="setting-card master-card"><div><span class="setting-icon">✦</span><div><h2>Intelligent styring</h2><p>Brug pris, vejr, forbrugsmønster og nettariffer til næste dags batteriplan.</p></div></div><label class="switch"><input id="enabled" type="checkbox"><span></span></label></section>
<section class="settings-grid"><article class="setting-card"><label for="enabled-until"><span>Aktiv til og med</span><small>Lad feltet stå tomt for at fortsætte uden slutdato.</small></label><input id="enabled-until" type="date"></article><article class="setting-card"><label for="horizon"><span>Planhorisont</span><small>Der anvendes kun de timer, hvor prisdata findes.</small></label><select id="horizon"><option value="24">24 timer</option><option value="36">36 timer</option><option value="48">48 timer</option></select></article><article class="setting-card fallback-card"><label><span>Standardtilstand uden plan</span><small>Anvendes når en plan udløber, automatikken stoppes eller data mangler.</small></label><div class="mode-options"><label><input type="radio" name="fallback" value="battery_first"><span><b>Battery First</b><small>Solenergi prioriteres til batteriet. AC-ladning er slået fra.</small></span></label><label><input type="radio" name="fallback" value="load_first"><span><b>Load First</b><small>Husets aktuelle forbrug prioriteres før batteriet.</small></span></label></div></article><article class="setting-card status-card"><span>Aktuel status</span><b id="automation-status">Henter indstillinger…</b><small id="last-plan">—</small></article></section>
<section class="save-panel"><div><b>Sikker automatisk drift</b><small>Planen begrænses fortsat af batteriets SOC-, effekt- og registergrænser.</small></div><button type="submit" id="save-settings">Gem indstillinger</button></section><p id="form-message" role="status"></p></form>
</main></div></body></html>
