<?php
declare(strict_types=1);
/** @var array $state */
$kw = static fn (float|int $w): string => number_format(abs((float) $w) / 1000, 2, ',', '.') . ' kW';
$batteryText = $state['battery_power_w'] > 50 ? 'Batteriet aflader til huset' : ($state['battery_power_w'] < -50 ? 'Batteriet oplades' : 'Batteriet er i hvile');
$gridText = $state['grid_power_w'] > 50 ? 'Der importeres fra elnettet' : ($state['grid_power_w'] < -50 ? 'Der eksporteres til elnettet' : 'Næsten intet netflow');
?>
<!doctype html><html lang="da" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#071713"><title>Solportalen</title><link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/assets/css/app.css"><script src="/assets/js/app.js" defer></script></head>
<body class="<?= $wallboard ? 'wallboard' : '' ?>" data-mode="<?= htmlspecialchars($mode, ENT_QUOTES) ?>">
<header><div class="brand"><span class="sunmark">☀</span><div><strong>Solportalen</strong><small>Lokal energi. Fuld kontrol.</small></div></div><div class="status"><span class="pill simulated"><?= $mode === 'simulator' ? 'SIMULATOR' : 'GROWATT RS485' ?></span><span class="pill shadow">READ ONLY</span><span class="live-dot"></span><span id="clock"></span></div></header>
<div class="layout">
<?php if (!$wallboard): ?><nav><a class="active" href="/">Overblik</a><a href="#priser">Priser &amp; tariffer</a><a href="#plan">Plan</a><a href="#historik">Historik</a><a href="#batteri">Batteri</a><a href="#enheder">Enheder</a><a href="#styring">Manuel styring</a><a href="#commissioning">Commissioning</a><a href="#diagnostik">RS485-diagnostik</a><a href="#alarmer">Alarmer</a><a href="/wallboard">Wallboard</a></nav><?php endif; ?>
<main>
<section class="hero"><div><p class="eyebrow">SYSTEMET LIGE NU</p><h1 id="headline"><?= $online ? 'Live forbindelse til Growatt' : 'Venter på friske inverterdata' ?></h1><p id="summary"><?= $online ? 'Read-only Modbus-data opdateres lokalt gennem RS485.' : 'Kontrollér device-worker og serieport, hvis tilstanden fortsætter.' ?></p></div><div class="safe"><span><?= $online ? '✓' : '!' ?></span><div><b id="connection-status"><?= $online ? 'Forbundet' : 'Data mangler' ?></b><small>Modbus-writes er deaktiveret</small></div></div></section>
<section class="metrics"><article><span>Solproduktion</span><b id="pv"><?= $kw($state['pv_power_w']) ?></b><small>Målt via RS485</small></article><article><span>Husets forbrug</span><b id="load"><?= $kw($state['load_power_w']) ?></b><small>Growatt registermapping</small></article><article><span>Batteri</span><b id="battery"><?= $kw($state['battery_power_w']) ?></b><small><i style="--soc:<?= (float)$state['battery_soc_pct'] ?>%"></i><span id="soc"><?= number_format((float)$state['battery_soc_pct'], 0) ?> % SOC</span></small></article><article><span>El-net</span><b id="grid"><?= $kw($state['grid_power_w']) ?></b><small id="grid-direction"><?= $state['grid_power_w'] >= 0 ? 'Import' : 'Eksport' ?></small></article><article class="price"><span>Samlet købspris</span><b>— <em>DKK/kWh</em></b><small>Prisprovider ikke aktiveret</small></article></section>
<section class="grid"><article class="flow"><div class="section-title"><div><p class="eyebrow">ENERGIFLOW</p><h2>Strømmen finder den bedste vej</h2></div><span>Opdateret nu</span></div><div class="flowmap"><div class="node solar">☀<b>Sol</b><strong id="flow-pv"><?= $kw($state['pv_power_w']) ?></strong></div><div class="line horizontal"></div><div class="node home">⌂<b>Hus</b><strong><?= $kw($state['load_power_w']) ?></strong></div><div class="line down"></div><div class="flow-bottom"><div class="node battery">◫<b>Batteri</b><strong><?= number_format((float)$state['battery_soc_pct'], 0) ?> %</strong></div><div class="node gridnode">⇅<b>Net</b><strong><?= $kw($state['grid_power_w']) ?></strong></div></div></div></article>
<aside><article class="answer now"><p class="eyebrow">HVAD SKER DER NU?</p><h3 id="battery-state"><?= $batteryText ?></h3><p id="grid-state"><?= $gridText ?></p></article><article class="answer why"><p class="eyebrow">HVORFOR VISER VI DET?</p><h3>Direkte, lokal måling</h3><p>Værdierne læses read-only fra inverteren. Solportalen styrer endnu ikke anlægget.</p></article><article class="answer next"><p class="eyebrow">NÆSTE HANDLING</p><h3>Kun overvågning</h3><p>Automatik og Modbus-writes forbliver deaktiveret under commissioning.</p></article></aside></section>
<section class="plan" id="plan"><div class="section-title"><div><p class="eyebrow">LIVE</p><h2>Effekt de seneste minutter</h2></div><b id="sample-count">0 målepunkter</b></div><canvas id="chart" height="170" aria-label="Live effektgraf"></canvas></section>
</main></div><footer><span id="footer-source"><?= $mode === 'simulator' ? 'Data er simulerede' : 'Live read-only RS485-data' ?></span> · Signalmapping er under commissioning · <a href="/healthz">Systemstatus</a></footer></body></html>
