<?php
declare(strict_types=1);
$escape=static fn(mixed $value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$local=static fn(string $value,string $format):string=>(new DateTimeImmutable($value,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Europe/Copenhagen'))->format($format);
$weather=$insights['weather']??[];$prices=$insights['prices']??[];$tax=$insights['electricity_tax']??[];
?>
<!doctype html><html lang="da" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#06110e"><title><?= $forecastType==='weather'?'Vejrprognose':'Elprisprognose' ?> · Solportalen</title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/forecast.css"></head>
<body><header><a class="brand" href="/"><span class="sunmark">☀</span><span><b>Solportalen</b><small>Lokal energi. Fuld kontrol.</small></span></a><div class="status"><span class="pill read-pill">FORECAST</span></div></header>
<div class="layout"><nav><div class="nav-label">PROGNOSER</div><a href="/"><span>←</span>Overblik</a><a class="<?= $forecastType==='weather'?'active':'' ?>" href="/weather"><span>☀</span>Vejrprognose</a><a class="<?= $forecastType==='prices'?'active':'' ?>" href="/prices"><span>↗</span>Elprisprognose</a><a href="/suppliers"><span>⌕</span>Leverandørvagt</a><a href="/#plan"><span>✦</span>Godkendt plan</a><div class="nav-safety"><i></i><div><b>Sikker tilstand</b><small>Load First uden gyldig plan</small></div></div></nav><main class="forecast-page">
<?php if($forecastType==='weather'): ?>
<section class="forecast-hero"><p class="eyebrow">YR · <?= $escape($insights['location']??'Værløse') ?></p><h1>Vejr og forventet solproduktion</h1><p>Timeprognosen viser temperatur, skydække, nedbør og Solportalens beregnede solpotentiale.</p></section>
<section class="weather-grid"><?php foreach($weather as $item): ?><article><time><?= $escape($local((string)$item['forecast_at'],'D H:i')) ?></time><strong><?= number_format((float)$item['temperature_c'],1,',','.') ?>°</strong><progress class="solar-meter" max="100" value="<?= max(0,min(100,(float)$item['solar_score'])) ?>"></progress><b><?= number_format((float)$item['solar_score'],0,',','.') ?> / 100 sol</b><small><?= number_format((float)$item['cloud_pct'],0,',','.') ?> % skyer · <?= number_format((float)$item['precipitation_mm'],1,',','.') ?> mm<br><?= number_format((float)$item['expected_pv_w']/1000,2,',','.') ?> kW forventet</small></article><?php endforeach; ?></section>
<?php else: ?>
<section class="forecast-hero"><p class="eyebrow">DK2 · 15 MINUTTER</p><h1>Samlet elpris</h1><p>Spotpris, net-tarif, årsudjævnet elvarmeafgift og moms vises for hvert tilgængeligt interval.</p></section>
<aside class="tax-note"><b>Elvarmeafgift fordelt over året</b><span>Første <?= number_format((float)($tax['threshold_kwh']??4000),0,',','.') ?> kWh til fuld sats, resten til reduceret sats. Blandet afgift: <?= number_format((float)($tax['blended_rate_dkk_kwh_ex_vat']??0),3,',','.') ?> kr./kWh ekskl. moms ved <?= number_format((float)($tax['annual_consumption_kwh']??0),0,',','.') ?> kWh/år.</span></aside>
<section class="price-table"><table><thead><tr><th>Tid</th><th>Spot</th><th>Net</th><th>Elafgift</th><th>Samlet inkl. moms</th></tr></thead><tbody><?php foreach($prices as$item): ?><tr><td><?= $escape($local((string)$item['interval_start'],'D d/m H:i')) ?></td><td><?= number_format((float)$item['spot_dkk_kwh'],3,',','.') ?></td><td><?= number_format((float)$item['tariff_dkk_kwh'],3,',','.') ?></td><td><?= number_format((float)$item['tax_dkk_kwh'],3,',','.') ?></td><td><b><?= number_format((float)$item['total_dkk_kwh'],3,',','.') ?> kr.</b></td></tr><?php endforeach; ?></tbody></table></section>
<?php endif; ?>
<?php if(($forecastType==='weather'&&$weather===[])||($forecastType==='prices'&&$prices===[])): ?><div class="empty-state"><b>Prognosen er ikke hentet endnu</b><span>Kør scheduler-jobbet, og genindlæs derefter siden.</span></div><?php endif; ?>
</main></div></body></html>
