<?php
declare(strict_types=1);
namespace Solportalen\Integration\Ocpp;
use PDO;use RuntimeException;use Solportalen\Config\Env;
final class OcppServer{
 public function __construct(private PDO $pdo){}
 public function run():void{$port=(int)Env::get('OCPP_PORT','9000');$server=stream_socket_server("tcp://0.0.0.0:$port",$errno,$error);if(!$server)throw new RuntimeException($error);fwrite(STDOUT,"OCPP lytter på 0.0.0.0:$port\n");while($socket=@stream_socket_accept($server,-1,$peer)){$this->client($socket,$peer);}}
 private function client($s,string$peer):void{stream_set_timeout($s,30);$request='';while(!str_contains($request,"\r\n\r\n")&&!feof($s))$request.=fread($s,2048);if(!preg_match('#^GET\s+([^\s]+)#',$request,$m)||!preg_match('/Sec-WebSocket-Key:\s*(.+)\r\n/i',$request,$k)){fclose($s);return;}$user=Env::get('OCPP_USER','teison');$pass=Env::get('OCPP_PASSWORD','');if($pass!==''&&!str_contains($request,'Authorization: Basic '.base64_encode($user.':'.$pass))){fwrite($s,"HTTP/1.1 401 Unauthorized\r\nWWW-Authenticate: Basic realm=\"Solportalen\"\r\nContent-Length: 0\r\n\r\n");fclose($s);return;}$id=trim(basename(parse_url($m[1],PHP_URL_PATH)?:'teison'));$accept=base64_encode(sha1(trim($k[1]).'258EAFA5-E914-47DA-95CA-C5AB0DC85B11',true));fwrite($s,"HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: $accept\r\nSec-WebSocket-Protocol: ocpp1.6\r\n\r\n");while(!feof($s)){try{$text=$this->readFrame($s);if($text===null)break;$msg=json_decode($text,true,32,JSON_THROW_ON_ERROR);if(($msg[0]??null)!==2)continue;[$type,$uid,$action,$payload]=$msg;$this->record($id,$peer,$action,$payload);$reply=match($action){'BootNotification'=>['status'=>'Accepted','currentTime'=>gmdate('Y-m-d\TH:i:s\Z'),'interval'=>30],'Heartbeat'=>['currentTime'=>gmdate('Y-m-d\TH:i:s\Z')],'Authorize'=>['idTagInfo'=>['status'=>'Accepted']],'StartTransaction'=>['transactionId'=>time(),'idTagInfo'=>['status'=>'Accepted']],'StatusNotification','MeterValues','StopTransaction','DataTransfer'=>[],default=>[]};fwrite($s,$this->frame(json_encode([3,$uid,$reply],JSON_THROW_ON_ERROR)));}catch(\Throwable $e){break;}}fclose($s);}
 private function record(string$id,string$peer,string$action,array$p):void{$ip=explode(':',$peer)[0];$q=$this->pdo->prepare('INSERT INTO ocpp_messages(charge_point_id,action,payload_json,received_at) VALUES(?,?,?,UTC_TIMESTAMP(6))');$q->execute([$id,$action,json_encode($p,JSON_THROW_ON_ERROR)]);$status=$action==='StatusNotification'?($p['status']??'Unknown'):'Unknown';$q=$this->pdo->prepare('INSERT INTO ocpp_charge_points(charge_point_id,remote_ip,status,vendor,model,serial_number,last_seen_at) VALUES(?,?,?,?,?,?,UTC_TIMESTAMP(6)) ON DUPLICATE KEY UPDATE remote_ip=VALUES(remote_ip),status=IF(VALUES(status)="Unknown",status,VALUES(status)),vendor=COALESCE(VALUES(vendor),vendor),model=COALESCE(VALUES(model),model),serial_number=COALESCE(VALUES(serial_number),serial_number),last_seen_at=VALUES(last_seen_at)');$q->execute([$id,$ip,$status,$p['chargePointVendor']??null,$p['chargePointModel']??null,$p['chargePointSerialNumber']??null]);}
 private function readFrame($s):?string{$h=fread($s,2);if(strlen($h)<2)return null;$len=ord($h[1])&127;if($len===126)$len=unpack('n',fread($s,2))[1];elseif($len===127){$x=unpack('N2',fread($s,8));$len=$x[2];}$masked=(ord($h[1])&128)!==0;$mask=$masked?fread($s,4):'';$data='';while(strlen($data)<$len){$c=fread($s,$len-strlen($data));if($c==='')return null;$data.=$c;}if($masked)for($i=0;$i<$len;$i++)$data[$i]=$data[$i]^$mask[$i%4];return$data;}
 private function frame(string$d):string{$l=strlen($d);return chr(129).($l<126?chr($l):chr(126).pack('n',$l)).$d;}
}
