CREATE TABLE IF NOT EXISTS cloud_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, verified_at DATETIME NULL,
 session_version INT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS cloud_tokens (
 token_hash CHAR(64) PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 purpose VARCHAR(12) NOT NULL, expires_at DATETIME NOT NULL, used_at DATETIME NULL,
 FOREIGN KEY(user_id) REFERENCES cloud_users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS cloud_limits (
 bucket CHAR(64) PRIMARY KEY, attempts INT NOT NULL, expires_at DATETIME NOT NULL
);
CREATE TABLE IF NOT EXISTS cloud_mail (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, recipient VARCHAR(254) NOT NULL,
 subject VARCHAR(150) NOT NULL, body TEXT NOT NULL, attempts INT NOT NULL DEFAULT 0,
 sent_at DATETIME NULL, next_attempt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS cloud_installations (
 id CHAR(32) PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(80) NOT NULL,
 pair_hash CHAR(64) NULL UNIQUE, pair_expires DATETIME NULL, token_hash CHAR(64) NULL UNIQUE,
 share_public BOOLEAN NOT NULL DEFAULT 0, control_allowed BOOLEAN NOT NULL DEFAULT 0,
 last_seen DATETIME NULL, sample_at DATETIME NULL, state_json JSON NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES cloud_users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS cloud_samples (
 installation_id CHAR(32) NOT NULL, captured_at DATETIME NOT NULL,
 pv_w DECIMAL(12,2) NULL, load_w DECIMAL(12,2) NULL, grid_w DECIMAL(12,2) NULL,
 battery_w DECIMAL(12,2) NULL, soc DECIMAL(6,2) NULL,
 PRIMARY KEY(installation_id,captured_at), INDEX(captured_at),
 FOREIGN KEY(installation_id) REFERENCES cloud_installations(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS cloud_commands (
 id CHAR(32) PRIMARY KEY, installation_id CHAR(32) NOT NULL, mode VARCHAR(30) NOT NULL,
 duration_minutes INT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL,
 result_json JSON NULL, completed_at DATETIME NULL,
 INDEX(installation_id,status), FOREIGN KEY(installation_id) REFERENCES cloud_installations(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS cloud_audit (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL,
 installation_id CHAR(32) NULL, action VARCHAR(60) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
