<?php
declare(strict_types=1);
namespace Solportalen\Repository;
use PDO;
final class HistoryRepository{
 private const SIGNALS=['pv_power_w','load_power_w','battery_power_w','grid_power_w','battery_soc_pct'];
 public function __construct(private PDO $pdo){}
 public function aggregate():int{$names="'".implode("','",self::SIGNALS)."'";$sql="INSERT INTO energy_history_15m(bucket_start,signal_name,avg_value,min_value,max_value,sample_count,energy_kwh,source,updated_at) SELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(source_timestamp)/900)*900),signal_name,AVG(value_decimal),MIN(value_decimal),MAX(value_decimal),COUNT(*),IF(signal_name LIKE '%_power_w',AVG(value_decimal)*0.25/1000,NULL),MAX(source),UTC_TIMESTAMP(6) FROM telemetry WHERE value_decimal IS NOT NULL AND signal_name IN ($names) AND source_timestamp>=UTC_TIMESTAMP()-INTERVAL 2 DAY GROUP BY 1,2 ON DUPLICATE KEY UPDATE avg_value=VALUES(avg_value),min_value=VALUES(min_value),max_value=VALUES(max_value),sample_count=VALUES(sample_count),energy_kwh=VALUES(energy_kwh),source=VALUES(source),updated_at=VALUES(updated_at)";return(int)$this->pdo->exec($sql);}
 public function retain():array{$raw=$this->pdo->exec('DELETE FROM telemetry WHERE source_timestamp<UTC_TIMESTAMP()-INTERVAL 24 MONTH');$history=$this->pdo->exec('DELETE FROM energy_history_15m WHERE bucket_start<UTC_TIMESTAMP()-INTERVAL 24 MONTH');return['raw_deleted'=>(int)$raw,'history_deleted'=>(int)$history];}
 public function series(string$range='24h'):array{$hours=['24h'=>24,'7d'=>168,'30d'=>720,'12m'=>8760,'24m'=>17520][$range]??24;$step=$hours<=24?1:($hours<=168?4:($hours<=720?16:96));$q=$this->pdo->prepare("SELECT MIN(bucket_start) bucket_start,signal_name,AVG(avg_value) value,MIN(min_value) min_value,MAX(max_value) max_value,SUM(energy_kwh) energy_kwh FROM energy_history_15m WHERE bucket_start>=UTC_TIMESTAMP()-INTERVAL ? HOUR GROUP BY FLOOR(UNIX_TIMESTAMP(bucket_start)/(?*900)),signal_name ORDER BY bucket_start");$q->execute([$hours,$step]);$points=[];foreach($q->fetchAll()as$r){$time=gmdate(DATE_ATOM,strtotime($r['bucket_start'].' UTC'));$points[$time]['timestamp']=$time;$points[$time][$r['signal_name']]=(float)$r['value'];$points[$time][$r['signal_name'].'_min']=(float)$r['min_value'];$points[$time][$r['signal_name'].'_max']=(float)$r['max_value'];}return['range'=>$range,'retention_months'=>24,'resolution_minutes'=>$step*15,'points'=>array_values($points)];}
}
