<section class="guide-hero"><p class="eyebrow">DIN GUIDE FRA START TIL SOL</p><h1>Forbind dit hjem.<br><em>Behold kontrollen.</em></h1><p class="intro">En Raspberry Pi samler data fra dit anlæg og deler dem sikkert med din konto. Den lokale styring fortsætter, selvom internettet forsvinder.</p><div class="actions"><a class="button" href="/downloads/solportalen-installationsguide.pdf">Download PDF-guide ↓</a><a class="button secondary" href="/downloads/solportalen-pi.tar.gz">Download Pi-software ↓</a><a href="/downloads/SHA256SUMS">SHA-256</a></div></section>
<div class="guide-grid"><aside class="panel"><h3>Det skal du bruge</h3><ul><li>Raspberry Pi med Raspberry Pi OS / Debian, 64-bit</li><li>Stabil strøm, netværk og SD-kort eller SSD</li><li>SSH eller et tastatur til Pi’en</li><li>Et understøttet Growatt SPH-anlæg</li><li>Passende isoleret USB–RS485-adapter og modelspecifikt kabel</li><li>En e-mailadresse, du kan bekræfte</li></ul><p class="fine">Andre invertermodeller er ikke automatisk kompatible. Åbn ikke elinstallationer. Lad en fagperson håndtere kabelføring, hvis du er i tvivl.</p></aside><div class="steps">
<article class="panel"><span class="number">01</span><h2>Opret din konto</h2><p>Vælg <a href="/?page=register">Opret konto</a>, bekræft e-mailen og log ind. Tilføj et anlæg under Mit anlæg — du får en parringskode, som gælder i 15 minutter.</p></article>
<article class="panel"><span class="number">02</span><h2>Klargør din Raspberry Pi</h2><p>Installer et opdateret 64-bit Raspberry Pi OS. Aktivér SSH, opret din egen bruger, og forbind Pi’en til netværket. Log ind med <code>ssh BRUGER@PI-ADRESSE</code>. Der skal ikke åbnes porte i routeren.</p></article>
<article class="panel"><span class="number">03</span><h2>Hent og kontrollér softwaren</h2><pre>mkdir -p ~/solportalen-install
cd ~/solportalen-install
curl -fLO https://solpanel.linder.dk/downloads/solportalen-pi.tar.gz
curl -fLO https://solpanel.linder.dk/downloads/SHA256SUMS
sha256sum --check SHA256SUMS
tar -xzf solportalen-pi.tar.gz
cd solportalen
sudo sh scripts/install-raspberry-pi.sh</pre><p>Fortsæt kun, når kontrollen viser <strong>OK</strong>. Installeren sætter Apache, PHP, MariaDB og lokale services op — uden Composer. Nye installationer starter uden writes. Eksisterende indstillinger og historik bevares.</p></article>
<article class="panel"><span class="number">04</span><h2>Bekræft lokale målinger</h2><p>Åbn Pi’ens IP-adresse i din browser. Kontrollér serieport, solproduktion, batteriniveau og netmåling mod anlæggets eget display. Tilslut kun RS485 efter manualen til præcis din model; RJ45-formen betyder ikke Ethernet.</p><pre>systemctl status solportal-device --no-pager
journalctl -u solportal-device -n 30 --no-pager</pre><p class="fine">En allerede kørende device-worker ejer serieporten. Start ikke endnu en Modbus-test samtidig.</p></article>
<article class="panel"><span class="number">05</span><h2>Forbind til din konto</h2><pre>sudo -u solportal php /opt/solportalen/bin/solportal cloud:pair
sudo systemctl enable --now solportal-cloud</pre><p>Indtast parringskoden fra Mit anlæg, når du bliver spurgt. Koden sendes over HTTPS og byttes til en enhedsnøgle, som kun gemmes lokalt. Efter kort tid kommer målingerne frem på telefonen.</p></article>
<article class="panel"><span class="number">06</span><h2>Vælg, om du vil fjernstyre</h2><p>Start med overvågning. Når dit anlæg er lokalt afprøvet og writes er aktiveret, kan du give portalen lov til tidsbegrænsede modeændringer:</p><pre>sudo -u solportal php /opt/solportalen/bin/solportal cloud:control enable</pre><p>Brug <code>cloud:control disable</code> for at tilbagekalde tilladelsen. Det aktiverer aldrig Modbus-writes af sig selv. En manuel mode varer 15–120 minutter; derefter vælges den lokale standardmode, og automatisk planlægning kan fortsætte.</p></article>
<article class="panel"><h2>Hvis noget driller</h2><p><strong>Ingen mail?</strong> Se spam, vent et øjeblik, og brug Send nyt bekræftelseslink. <strong>Ingen data?</strong> Kontrollér lokal drift og <code>journalctl -u solportal-cloud -n 30</code>. <strong>Udløbet kode?</strong> Opret en ny i panelet. <strong>Mode står i kø?</strong> Det er ikke en kvittering; vent på verificeret eller fejl. <strong>Offline?</strong> Gamle tal markeres som gamle, ikke som nul.</p></article>
</div></div>
