<!doctype html>
<html lang="da"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#082d28"><title>Solportalen · Din energi. Dit overblik.</title><meta name="description" content="Forbind dit solanlæg med Solportalen. Lokal styring, et enkelt mobilt overblik og et fællesskab om solenergi."><link rel="stylesheet" href="/assets/portal.css"><script src="/assets/portal.js" defer></script></head>
<body data-page="<?=e($page)?>"><header><a class="brand" href="/">✳ <span>Solportalen<small>Din energi. Dit overblik.</small></span></a><nav aria-label="Hovedmenu"><a href="/?page=guide">Kom i gang</a><?php if($user): ?><a href="/?page=dashboard">Mit anlæg</a><form method="post"><?=csrf()?><button name="action" value="logout" class="quiet">Log ud</button></form><?php else: ?><a href="/?page=login">Log ind</a><a class="button small" href="/?page=register">Opret konto ↗</a><?php endif; ?></nav></header>
<main>
<?php if($notice): ?><div class="notice" role="status"><?=e($notice)?></div><?php endif; ?>
<?php if($error): ?><div class="notice error" role="alert"><?=e($error)?></div><?php endif; ?>
<?php if($page==='home'): ?>
<section class="hero"><div><p class="eyebrow">LOKAL INTELLIGENS · FÆLLES SOLENERGI</p><h1>Få mere ud<br>af <em>din sol.</em></h1><p class="intro">Fra solstråle til stikkontakt. Følg dit anlæg, forstå din energi og behold kontrollen — også når du ikke er hjemme.</p><div class="actions"><a class="button" href="/?page=register">Forbind dit anlæg ↗</a><a class="text-link" href="/?page=guide">Sådan fungerer det →</a></div><p class="muted">Raspberry Pi · Growatt SPH · Ingen åbne porte i din router</p></div>
<div class="solar-scene" aria-label="Illustration: solen forsyner hjem og batteri, mens Pi’en holder overblikket"><div class="orbit one"></div><div class="orbit two"></div><div class="sun">☀</div><div class="scene-node solar">SOLENERGI<span>Produceret hos dig</span></div><div class="scene-node home">DIT HJEM<span>Overblik over forbruget</span></div><div class="scene-node storage">DIT BATTERI<span>Energi til senere</span></div><div class="core"><span>✳</span><strong>Solportalen</strong><small>Lokal styring. Online overblik.</small></div><p class="scene-caption">Illustration — ingen fiktive målinger</p></div></section>
<section class="community panel"><div class="section-heading"><div><p class="eyebrow">SOLEN ARBEJDER FOR OS ALLE</p><h2>Dagens fælles solhøst</h2></div><span class="pill">Frivillig datadeling</span></div><div class="community-grid"><div><div class="huge" id="community-total">—</div><p class="muted">kWh i offentliggjorte intervaller i dag</p><p id="community-status">Henter fællesskabets produktion…</p></div><div><svg id="community-chart" class="chart" viewBox="0 0 720 230" role="img" aria-label="Samlet solenergi i halve timer"></svg><p class="muted">30-minutters intervaller · mindst 30 minutters forsinkelse · dansk tid</p></div></div><p class="fine">Vi offentliggør kun grupper med mindst fem tilmeldte anlæg. Ingen navne, adresser eller individuelle forbrugskurver. Tallene er estimater fra modtagne målinger; huller udfyldes ikke.</p></section>
<section class="three"><article class="feature"><span class="number">01</span><h3>Dit anlæg bliver hjemme</h3><p>Pi’en passer den lokale styring. Portalen får kun de data og rettigheder, du vælger at dele.</p></article><article class="feature"><span class="number">02</span><h3>Overblik i lommen</h3><p>Sol, forbrug, batteri og net i ét mobilvenligt dashboard. Med tidsstempler, så du kan se, om data er friske.</p></article><article class="feature"><span class="number">03</span><h3>Du bestemmer retningen</h3><p>Vælg en midlertidig mode. Pi’en kontrollerer grænserne og melder tilbage, når ændringen er verificeret.</p></article></section>
<section class="cta"><div><p class="eyebrow">FRA SD-KORT TIL SOLOVERBLIK</p><h2>Klar til at forbinde dit anlæg?</h2><p>Vi tager dig gennem installationen, ét trin ad gangen.</p></div><a class="button" href="/?page=guide">Åbn installationsguiden →</a></section>
<?php elseif(in_array($page,['register','login','forgot','resend','reset','verify'],true)): ?>
<section class="auth panel"><p class="eyebrow">VELKOMMEN I SOLPORTALEN</p><h1><?=e(['register'=>'Plads til din energi.','login'=>'Velkommen tilbage.','forgot'=>'Glemt adgangskoden?','resend'=>'Et nyt bekræftelseslink.','reset'=>'Vælg en ny adgangskode.','verify'=>'Bekræft din e-mail.'][$page])?></h1>
<?php if($page==='register' && empty($config['registration_enabled'])): ?>
<p class="notice" role="status">Vi klargør den sidste del af mailleveringen. Nye konti åbner snart.</p><p>Du kan allerede læse <a href="/?page=guide">installationsguiden og hente softwaren</a>.</p>
<?php else: ?>
<form method="post"><?=csrf()?><input type="hidden" name="action" value="<?=e($page)?>">
<?php if(in_array($page,['register','login','forgot','resend'],true)): ?><label>E-mail<input name="email" type="email" autocomplete="email" maxlength="254" required></label><?php endif; ?>
<?php if(in_array($page,['login','register','reset'],true)): ?><label>Adgangskode<input name="password" type="password" autocomplete="<?=$page==='login'?'current-password':'new-password'?>" <?=$page==='login'?'':'minlength="12"'?> maxlength="72" required></label><?php endif; ?>
<?php if(in_array($page,['register','reset'],true)): ?><p class="muted">Mindst 12 tegn. Brug gerne en lang, unik sætning.</p><label>Gentag adgangskoden<input name="password_confirm" type="password" autocomplete="new-password" minlength="12" maxlength="72" required></label><?php endif; ?>
<?php if(in_array($page,['verify','reset'],true)): ?><input type="hidden" id="link-token" name="token"><p>Linket kan kun bruges én gang. Tryk herunder for at fortsætte.</p><?php endif; ?>
<?php if($page==='register'): ?><p class="fine">Vi sender et bekræftelseslink. Dit anlæg deles ikke offentligt uden dit tilvalg. Læs <a href="/?page=privacy">om data og privatliv</a>.</p><?php endif; ?>
<button class="button"><?=e(['register'=>'Opret konto →','login'=>'Log ind →','forgot'=>'Send nulstillingslink','resend'=>'Send bekræftelseslink','reset'=>'Gem ny adgangskode','verify'=>'Bekræft e-mail'][$page])?></button></form>
<?php endif; ?>
<div class="auth-links"><a href="/?page=forgot">Glemt kode?</a><a href="/?page=resend">Mangler bekræftelsen?</a><a href="/?page=register">Ny konto</a></div></section>
<?php elseif($page==='dashboard'): ?>
<section class="section-heading"><div><p class="eyebrow">DIT PRIVATE ENERGIOVERBLIK</p><h1>Hej, solfanger.</h1><p class="muted"><?=e($user['email'])?></p></div><a href="/?page=guide" class="button secondary">Forbind en Pi →</a></section>
<?php if($pair): ?><section class="notice"><strong>Parringskode — gyldig i 15 minutter</strong><pre><?=e($pair['code'])?></pre><p>Kør på Pi’en: <code>sudo -u solportal php /opt/solportalen/bin/solportal cloud:pair</code>. Indtast koden, når du bliver spurgt. Den vises kun denne gang.</p></section><?php endif; ?>
<details class="panel" <?=$installations?'':'open'?>><summary>Tilføj et anlæg</summary><form method="post" class="inline-form"><?=csrf()?><input type="hidden" name="action" value="create"><label>Navn<input name="name" maxlength="80" placeholder="Mit solanlæg" required></label><button class="button">Opret parringskode</button></form></details>
<?php if($selected): $state=json_decode($selected['state_json']??'{}',true); ?>
<nav class="tabs" aria-label="Dine anlæg"><?php foreach($installations as $d): ?><a class="<?=$d['id']===$selected['id']?'active':''?>" href="/?page=dashboard&amp;id=<?=e($d['id'])?>"><?=e($d['name'])?></a><?php endforeach; ?></nav>
<div id="device" data-id="<?=e($selected['id'])?>"><div class="section-heading"><h2><?=e($selected['name'])?></h2><span class="pill" id="freshness">Afventer måling</span></div>
<section class="metrics"><article class="panel"><span>Sol lige nu</span><strong id="pv">—</strong></article><article class="panel"><span>Husets forbrug</span><strong id="load">—</strong></article><article class="panel"><span>Batteri</span><strong id="soc">—</strong><small id="battery">—</small></article><article class="panel"><span>Offentligt net</span><strong id="grid">—</strong><small>+ import / − eksport</small></article></section>
<section class="panel"><div class="section-heading"><div><p class="eyebrow">ENERGI OVER TID</p><h2>Anlæggets rytme</h2></div><label>Periode<select id="history-days"><option value="1">24 timer</option><option value="7">7 dage</option><option value="30">30 dage</option><option value="365">12 måneder</option><option value="730">24 måneder</option></select></label></div><p class="legend"><span class="yellow">● Sol</span><span class="green">● Hus</span><span class="blue">● Net</span><span class="purple">● Batteri</span> · kW</p><svg id="history-chart" class="chart large" viewBox="0 0 1000 310" role="img" aria-label="Historik for sol, forbrug, net og batteri"></svg><p class="muted" id="history-info">Henter historik…</p></section>
<section class="two"><article class="panel"><p class="eyebrow">KONTROLLERET FJERNSTYRING</p><h2>Aktuel mode: <span id="mode">—</span></h2><p id="override-status" class="muted"></p><p>En midlertidig mode sætter plananvendelse på pause. Ved udløb går Pi’en tilbage til lokal standardmode; intelligent styring kan derefter lægge en ny plan.</p><form method="post"><?=csrf()?><input type="hidden" name="action" value="mode"><input type="hidden" name="id" value="<?=e($selected['id'])?>"><label>Ønsket mode<select name="mode"><option value="battery_first">Gem sol · Battery First</option><option value="load_first">Forsyn huset · Load First</option><option value="charge_grid">Oplad fra net · Battery First med AC</option><option value="grid_first">Aflad til net · Grid First</option></select></label><label>Varighed<select name="minutes"><option value="15">15 minutter</option><option value="30">30 minutter</option><option value="60">1 time</option><option value="120">2 timer</option></select></label><label>Bekræft med din adgangskode<input type="password" name="password" autocomplete="current-password" required></label><button class="button">Send til min Pi</button></form><p class="fine">Kun med lokalt godkendte writes og fjernstyring. Batterigrænser bestemmes lokalt. Grid First kan eksportere strøm og tømme batteriet ned til den lokale reserve.</p></article><article class="panel"><p class="eyebrow">KVITTERINGER FRA ANLÆGGET</p><h2>Fra ønske til handling</h2><div id="commands" aria-live="polite">Ingen kommandoer endnu.</div><hr><form method="post"><?=csrf()?><input type="hidden" name="action" value="share"><input type="hidden" name="id" value="<?=e($selected['id'])?>"><label class="check"><input type="checkbox" name="share" <?=$selected['share_public']?'checked':''?>>Bidrag med solproduktion til den offentlige fællesgraf</label><p class="fine">Kun grupperede produktionstal. Dit navn, forbrug og batteri offentliggøres ikke. Kan slås fra igen.</p><button class="button secondary">Gem datadeling</button></form></article></section>
<details class="panel"><summary>Forbindelse og afkobling</summary><p>Afkobling stopper nye data og kommandoer. Historikken bliver på kontoen. En allerede udført mode udløber lokalt.</p><form method="post"><?=csrf()?><input type="hidden" name="id" value="<?=e($selected['id'])?>"><label>Adgangskode<input name="password" type="password" autocomplete="current-password"></label><button name="action" value="revoke">Afkobl Pi</button><?php if(!$selected['token_hash']): ?><button name="action" value="repair">Lav ny parringskode</button><?php endif; ?></form></details></div>
<?php else: ?><section class="panel empty"><h2>Her begynder dit energioverblik.</h2><p>Opret et anlæg ovenfor, og forbind din Raspberry Pi med parringskoden.</p></section><?php endif; ?>
<?php elseif($page==='guide'): require __DIR__.'/guide.php'; ?>
<?php elseif($page==='privacy'): ?>
<section class="panel prose"><p class="eyebrow">DATA & PRIVATLIV</p><h1>Din energi er din.</h1><h2>Hvad gemmer vi?</h2><p>Din e-mail, en hash af din adgangskode, anlægsnavn, målinger, driftsstatus og kommandokvitteringer. Energidata gemmes op til 24 måneder. Vi bruger en nødvendig login-cookie og ingen reklame- eller analysecookies.</p><h2>Offentlige tal er frivillige</h2><p>Datadeling er slået fra ved oprettelse. Hvis du tilvælger den, medregnes solproduktion i forsinkede halvtimesgrupper med mindst fem anlæg. Individuelle målinger, navne, adresser og forbrug vises ikke offentligt. Gruppering reducerer risikoen for genkendelse, men er ikke en garanti for fuldstændig anonymitet.</p><h2>Fjernstyring er et aktivt valg</h2><p>Du skal give tilladelse lokalt på Pi’en. Portalen får ikke SSH-adgang, Wi-Fi-koder eller rå Modbus-adgang. En tilbagekaldt forbindelse kan ikke hente nye kommandoer. En allerede udført midlertidig mode udløber på Pi’en.</p><h2>Kontakt og sletning</h2><p>Kontakt portalens administrator om indsigt, eksport eller sletning af din konto. Forbindelsen til Pi’en kan til enhver tid afkobles i dit dashboard. Den lokale installation fortsætter uafhængigt.</p></section>
<?php endif; ?>
</main><footer><a class="brand" href="/">✳ Solportalen</a><p>Lokal energi. Forbundet overblik.</p><a href="/?page=privacy">Data & privatliv</a><a href="/?page=guide">Installation & hjælp</a></footer></body></html>
